# 数据配置
data: "CACTUS/Images Dataset"
camus_data: "CAMUS"
task_type: "binary"
num_workers: 4

# 模型配置
num_classes: 7
batch_size: 32

# 评估配置
test_only: false
val_only: false
full_data: true
holdout_split: 0.1  # 保留比例（用于最终验证）
holdout_only: false  # 是否仅在Holdout集上评估
plot_cm: true
plot_roc: true
save_dir: "results"
fold: 0

# 随机种子
seed: 42
